{{- if .Values.global.notifications.alertConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  alerts.json: '{{ toJson .Values.global.notifications.alertConfigs }}'
{{- end -}}
